AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TakeNotes serverless web application
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 60
    Tracing: Active
    MemorySize: 1024
    Tags:
      Application: serverless-web-app
  Api:
    Auth:
      UsagePlan:
        UsagePlanName: DailyUsagePlan
        CreateUsagePlan: PER_API
        Description: This will limit 5000 executions per day and throttle executions on 10% of that.
        Quota:
          Limit: 5000
          Period: DAY
        Throttle:
          BurstLimit: 100
          RateLimit: 50
Parameters:
  VersionParam:
    Type: String
    Default: v1
  StageNameParam:
    Type: String
    Default: test
Resources:
  TakeNotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
        - "-"
        - - TakeNotes-table-test
          - !Ref AWS::StackName
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
  TakeNotesApi:
    Type: AWS::Serverless::Api
    MethodSettings:
      DataTraceEnabled: true
      MetricsEnabled: true
      HttpMethod: "*"
      ResourcePath: !Sub ${VersionParam}/*
      LoggingLevel: INFO
    AccessLogSetting:
      DestinationArn: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ApiAccessLogGroup}
      Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency $context.integrationLatency "$context.error.message"'
    Properties:
      Name: TakeNotesApi
      StageName: !Ref StageNameParam
      TracingEnabled: true
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
  GetTakeNotesUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: takeNotes-src/getUser
      Handler: app.getUser
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TakeNotesTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TakeNotesTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          USE_DYNAMODB_LOCAL: "0"
          DYNAMODB_LOCAL_URI: ""
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get
            RestApiId: !Ref TakeNotesApi
  PostTakeNotesUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: takeNotes-src/postUser/
      Handler: app.postUser
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TakeNotesTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TakeNotesTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /users/
            Method: POST
            RestApiId: !Ref TakeNotesApi
  PutTakeNotesUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: takeNotes-src/putUser/
      Handler: app.putUser
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TakeNotesTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TakeNotesTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""
      Events:
        PutUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: PUT
            RestApiId: !Ref TakeNotesApi
  DeleteTakeNotesUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: takeNotes-src/deleteUser/
      Handler: app.deleteUser
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TakeNotesTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TakeNotesTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: DELETE
            RestApiId: !Ref TakeNotesApi
  TakeNotesTestRequestGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: takeNotes-src/testRequest/
      Handler: app.testRequest
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TakeNotesTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TakeNotesTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""
      Events:
        TestReq:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref TakeNotesApi
  ApiGatewayPushToCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Push logs to CloudWatch logs from API Gateway
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/AccessLog-${TakeNotesApi}
      RetentionInDays: 365
Outputs:
  TakeNotesFunctionApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub https://${TakeNotesApi}.execute-api.${AWS::Region}.amazonaws.com/{StageNameParam}
