AWSTemplateFormatVersion: '2010-09-09' # this is the only value u can choose - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
Transform: AWS::Serverless-2016-10-31 # same with this - transform lets us specify how we want to process this template - in this case as serverless 
                                      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Description: "TakeNotes serverless web application"S
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals: # Below is stuff in common for each resource group
  Function: # common config for lamda functions 
    Runtime: nodejs12.x
    Timeout: 60 
    Tracing: Active
    MemorySize: 1024 # From Lambda Power Tuner - https://lambda-power-tuning.show/#gAAAAQACAAQACMAL;Fu+DQkrxg0JplAJBPCnQQBhL0EDm+NlA;m1ZfNJtW3zSbVl81m1bfNZtWXzaaA6Q2
    Tags:
      Application: serverless-web-app
  Api: # Common config for api gateway - all request go throughs this
    Auth:
      UsagePlan: 
        UsagePlanName: DailyUsagePlan
        CreateUsagePlan: PER_API
        Description: This will limit 5000 executions per day and throttle executions on 10% of that.
        Quota:
          Limit: 5000
          Period: DAY
        Throttle:
          BurstLimit: 100
          RateLimit: 50
# parameter are values you want to pass to template during runtime(when u build or update stack)
Parameters: # can be referenced as values using !ref
  VersionParam:
    Type: String
    Default: v1
  StageNameParam:
    Type: String
    Default: prod
  CognitoDomainName:
    Type: String
    Default: mytodoappdemo # need to update this

  # For Amplify Console frontend hosting
  Repository:
    Type: String
    Description: GitHub Repository URL
  Branch:
    Type: String
    Description: GitHub Branch
    Default: master # should be updated to main
  OauthToken:
    Type: String
    Description: GitHub Repository URL
    NoEcho: true

Resources: # aws stuff we want to provision

#cognito declaration
  TodoUserPool:
    Type: AWS::Cognito::UserPool # read more - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false # this lets users sign themselves up
      UserPoolName: TodoUsers # update name, also 
      UsernameAttributes: # set usernames to email or phone
      - email
      AutoVerifiedAttributes: # what needs to be verified
      - email
      Policies: # basically just password - see more https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: true
  
  TodoUserPoolTokenClient: # rename
    Type: AWS::Cognito::UserPoolClient # client is what our client side code will use - read more https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html
    Properties:
      UserPoolId: !Ref TodoUserPool # use our user pool made before - should be renamed
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: ['code', 'implicit'] # implict means we use their UI and jwt token is added to the callback url - read more https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-configuring-app-integration.html
                                              # code example look at how idToken is set - https://github.com/aws-samples/lambda-refarch-webapp/blob/master/www/src/App.js#L165 
      CallbackURLs: ['http://localhost:3000', 'http://localhost:8080' ,'https://localhost', !Join ['', ['https://', !GetAtt AmplifyBranch.BranchName, '.', !GetAtt AmplifyApp.DefaultDomain]]] # for implicit flow we need to return user back to our site
      SupportedIdentityProviders: ['COGNITO']
      AllowedOAuthScopes: ['phone', 'email', 'openid']
      ExplicitAuthFlows:
      - USER_PASSWORD_AUTH
  
  TodoDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: !Join ['-', [!Ref CognitoDomainName, !Ref AWS::StackName]]
      UserPoolId: !Ref TodoUserPool

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ['-', [users-table, !Ref AWS::StackName]]
      KeySchema:
          - AttributeName: cognito-username
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
      AttributeDefinitions:
          - AttributeName: cognito-username
            AttributeType: S
          - AttributeName: id
            AttributeType: S
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5                  
      SSESpecification:
        SSEEnabled: true

  # API declaration
  TodoApi: # this is implictly defined based on what functions we push - if we want to be explicit create a swagger definition of api
    Type: AWS::Serverless::Api # api gateway instance
    MethodSettings: 
        DataTraceEnabled: true
        MetricsEnabled: true
        HttpMethod: '*'
        ResourcePath: !Sub '${VersionParam}/*' # !sub is substitute - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
        LoggingLevel: INFO
    AccessLogSetting:
      DestinationArn: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ApiAccessLogGroup}'
      Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency $context.integrationLatency "$context.error.message"'
    Properties:
      Name: TodoApi
      StageName: !Ref StageNameParam
      TracingEnabled: true
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,HEAD,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "TodoUserPool.Arn"

  # API Functions
  GetTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties: # function is run with default IAM role created 
      CodeUri: todo-src/getTodo # relative url in folder
      Handler: app.getToDoItem 
      Tracing: Active
      Policies: # policies determine what we can access - if we create an IAM role we can reference that
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable 
        - CloudWatchPutMetricPolicy: {}
      Environment: #config for runtime env of lambda
        Variables:
          TABLE_NAME: !Ref TodoTable # update this
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          USE_DYNAMODB_LOCAL: "0"
          DYNAMODB_LOCAL_URI: ""

      Events:
        GetItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /item/{id}
            Method: get
            RestApiId: !Ref TodoApi
            Auth:
              Authorizer: CognitoAuthorizer

  GetAllTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todo-src/getAllTodo
      Handler: app.getAllToDoItem
      Tracing: Active
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""

      Events:
        GetItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /item
            Method: get
            RestApiId: !Ref TodoApi
            Auth:
              Authorizer: CognitoAuthorizer

  CompleteTodoFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: todo-src/completeTodo/
        Handler: app.completeToDoItem
        Tracing: Active
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TodoTable
          - CloudWatchPutMetricPolicy: {}
        Environment:
          Variables:
            TABLE_NAME: !Ref TodoTable
            AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
            ENDPOINT_OVERRIDE: ""

        Events:
          CompleteItem:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /item/{id}/done
              Method: post
              RestApiId: !Ref TodoApi
              Auth:
                Authorizer: CognitoAuthorizer

  AddTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todo-src/addTodo/
      Handler: app.addToDoItem
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""

      Events:
        PutItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /item
            Method: POST
            RestApiId: !Ref TodoApi
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateTodoFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: todo-src/updateTodo/
        Handler: app.updateToDoItem
        Tracing: Active
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref TodoTable
          - CloudWatchPutMetricPolicy: {}
        Environment:
          Variables:
            TABLE_NAME: !Ref TodoTable
            AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
        Events:
          UpdateItem:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /item/{id}
              Method: PUT
              RestApiId: !Ref TodoApi
              Auth:
                Authorizer: CognitoAuthorizer

  DeleteTodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todo-src/deleteTodo
      Handler: app.deleteToDoItem
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
        - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          TABLE_NAME: !Ref TodoTable # update this
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
          ENDPOINT_OVERRIDE: ""

      Events:
        DeleteItem:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /item/{id}
            Method: DELETE
            RestApiId: !Ref TodoApi # update
            Auth:
              Authorizer: CognitoAuthorizer

  # This role allows API Gateway to push execution and access logs to CloudWatch logs
  ApiGatewayPushToCloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: "Push logs to CloudWatch logs from API Gateway"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup # cloudwatch logs for logging
    Properties:
      LogGroupName: !Sub /aws/apigateway/AccessLog-${TodoApi} # update name
      RetentionInDays: 365 # how long to keep logs

  # Amplify console hosting for static website
  # 
  AmplifyRole: # creates role to let console perform build/deploy actions
    Type: AWS::IAM::Role # read more here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies: # the below basically let console do any action or access an resource
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"

  AmplifyApp:
    Type: "AWS::Amplify::App" # creates apps (app is collection of branches) in amplify console - see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html 
    Properties: 
      Name: TodoApp # update name
      Repository: !Ref Repository # link our github repo
      Description: Todo example app # update this
      OauthToken: !Ref OauthToken
      BuildSpec: |- # update this to be accurate to NEXT build
        version: 0.1
        frontend:
          phases:
            build:
              commands:
                - cd www/src
                - npm install
                - npm run build
          artifacts:
            baseDirectory: www/build/
            files:
              - '**/*'
      Tags:
        - Key: Name
          Value: Todo # update this
      IAMServiceRole: !GetAtt AmplifyRole.Arn # gets arn of role - arn is uniquer identifier for resource

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref Branch # referenced github branch
      AppId: !GetAtt AmplifyApp.AppId
      Description: Amplify Console Branch
      EnableAutoBuild: true
      Tags:
        - Key: Name
          Value: todo-amplify-console # update this
        - Key: Branch
          Value: !Ref Branch

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TodoFunctionApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/{StageNameParam}" # the TodoApi -> is an example of using logical ids as a reference - see more here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
  CognitoID:
    Description: The Cognito UserPool ID
    Value: !Ref TodoUserPool 
  CognitoClientID:
    Description: The Cognito UserPool Client ID
    Value: !Ref TodoUserPoolTokenClient
  CognitoDomainName:
    Description: The Cognito Hosted UI Domain Name
    Value: !Join ['', [!Ref CognitoDomainName, '-', !Ref AWS::StackName, '.auth.', !Ref AWS::Region, '.amazoncognito.com']]
  AmplifyURL:
    Value: !Join ['', ['https://', !GetAtt AmplifyBranch.BranchName, '.', !GetAtt AmplifyApp.DefaultDomain]]
